import React, { useState } from 'react'
import Navbar from './components/Navbar/Navbar'
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";

const App = () => {
  return (
    <div className='app'>
      <Router>
        <Navbar/>
        {/* <LoadingBar color="#f11946" progress={progress} />
        <Routes>
          <Route
            exact
            path="/"
            element={
              <News
                updateProgress={updateProgress}
                key="general"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="general"
              />
            }
          />
          <Route
            exact
            path="/newse"
            element={
              <News
                updateProgress={updateProgress}
                key="general"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="general"
              />
            }
          />
          <Route
            exact
            path="/business"
            element={
              <News
                updateProgress={updateProgress}
                key="business"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="business"
              />
            }
          />
          <Route
            exact
            path="/entertainment"
            element={
              <News
                updateProgress={updateProgress}
                key="entertainment"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="entertainment"
              />
            }
          />
          <Route
            exact
            path="/general"
            element={
              <News
                updateProgress={updateProgress}
                key="general"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="general"
              />
            }
          />
          <Route
            exact
            path="/health"
            element={
              <News
                updateProgress={updateProgress}
                key="health"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="health"
              />
            }
          />
          <Route
            exact
            path="/science"
            element={
              <News
                updateProgress={updateProgress}
                key="science"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="science"
              />
            }
          />
          <Route
            exact
            path="/technology"
            element={
              <News
                updateProgress={updateProgress}
                key="technology"
                pageSize={6}
                apiKey={apiKey}
                country="in"
                category="technology"
              />
            }
          />
        </Routes> */}
      </Router>
    </div>
  )
}

export default App